{
  "formatVersion": "1.0",
  "component": {
    "url": "../../squash-jdbc/0.1.4/squash-jdbc-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "squash-jdbc",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "squash-jdbc-jvm-0.1.4.jar",
          "url": "squash-jdbc-jvm-0.1.4.jar",
          "size": 36980,
          "sha1": "239fa56a62c1ce76130605f34ce071e799bd4717",
          "md5": "c58c6c822cb71bdc9852ecfa71a4c29"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "squash-jdbc-jvm-0.1.4.jar",
          "url": "squash-jdbc-jvm-0.1.4.jar",
          "size": 36980,
          "sha1": "239fa56a62c1ce76130605f34ce071e799bd4717",
          "md5": "c58c6c822cb71bdc9852ecfa71a4c29"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../squash-jdbc-metadata/0.1.4/squash-jdbc-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "squash-jdbc-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
