{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-api/0.1.4/kuick-api-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-api",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kuick-api-js-0.1.4.jar",
          "url": "kuick-api-js-0.1.4.jar",
          "size": 261,
          "sha1": "7a8a95c36b8a40461f5239f5c011d1660c8f7620",
          "md5": "44c10612c3e911b933446a968342dd5b"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-js-0.1.4.jar",
          "url": "kuick-api-js-0.1.4.jar",
          "size": 261,
          "sha1": "7a8a95c36b8a40461f5239f5c011d1660c8f7620",
          "md5": "44c10612c3e911b933446a968342dd5b"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-api-metadata/0.1.4/kuick-api-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-api-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
