{
  "formatVersion": "1.0",
  "component": {
    "url": "../../squash-graph/0.1.4/squash-graph-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "squash-graph",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.4.22"
          }
        }
      ],
      "files": [
        {
          "name": "squash-graph-jvm-0.1.4.jar",
          "url": "squash-graph-jvm-0.1.4.jar",
          "size": 70226,
          "sha1": "4fae11a2fd451742bc2d67b73969921b91b47849",
          "md5": "d0d40051158daf47c026c27717343887"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.4.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "squash-graph-jvm-0.1.4.jar",
          "url": "squash-graph-jvm-0.1.4.jar",
          "size": 70226,
          "sha1": "4fae11a2fd451742bc2d67b73969921b91b47849",
          "md5": "d0d40051158daf47c026c27717343887"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../squash-graph-metadata/0.1.4/squash-graph-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "squash-graph-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
