{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kuick-core/1.5-cherry/kuick-core-1.5-cherry.module",
    "group": "com.nospoonlab",
    "module": "kuick-core",
    "version": "1.5-cherry",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "otjt3l7bnjal3orczjznf72aji"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-core-js-1.5-cherry.jar",
          "url": "kuick-core-js-1.5-cherry.jar",
          "size": 141651,
          "sha512": "4225301da22692c9519df0ab305248b0c779b210088f24e10aba21c4e032f6b1987cb991b18fe8275a0f80e1bf64a07c70a6532eba58c757d0204a0373574ae0",
          "sha256": "a00ba44d6b30128daf9455ab7f489790f37f5effab4c5823dff28344b250dc40",
          "sha1": "07037422a3e08df893d914913be5e3b5b969fa9c",
          "md5": "3b72e13d7ec9546e4ed052252ef5462a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-core-js-1.5-cherry.jar",
          "url": "kuick-core-js-1.5-cherry.jar",
          "size": 141651,
          "sha512": "4225301da22692c9519df0ab305248b0c779b210088f24e10aba21c4e032f6b1987cb991b18fe8275a0f80e1bf64a07c70a6532eba58c757d0204a0373574ae0",
          "sha256": "a00ba44d6b30128daf9455ab7f489790f37f5effab4c5823dff28344b250dc40",
          "sha1": "07037422a3e08df893d914913be5e3b5b969fa9c",
          "md5": "3b72e13d7ec9546e4ed052252ef5462a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-core-metadata/1.5-cherry/kuick-core-metadata-1.5-cherry.module",
        "group": "com.nospoonlab",
        "module": "kuick-core-metadata",
        "version": "1.5-cherry"
      }
    }
  ]
}
