{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-http-ktor/0.1.4/kuick-http-ktor-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-http-ktor",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-locations",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-http-ktor-jvm-0.1.4.jar",
          "url": "kuick-http-ktor-jvm-0.1.4.jar",
          "size": 53980,
          "sha1": "9ff7ec868a4eb4b9fa9adf9edb87c46ae6746f85",
          "md5": "84fdfac88c88de6e4c3b6b812eb30b95"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-locations",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-http-ktor-jvm-0.1.4.jar",
          "url": "kuick-http-ktor-jvm-0.1.4.jar",
          "size": 53980,
          "sha1": "9ff7ec868a4eb4b9fa9adf9edb87c46ae6746f85",
          "md5": "84fdfac88c88de6e4c3b6b812eb30b95"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-http-ktor-metadata/0.1.4/kuick-http-ktor-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-http-ktor-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
