{
  "formatVersion": "1.0",
  "component": {
    "url": "../../squash-h2/0.1.4/squash-h2-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "squash-h2",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-graph",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-jdbc",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.197"
          }
        }
      ],
      "files": [
        {
          "name": "squash-h2-jvm-0.1.4.jar",
          "url": "squash-h2-jvm-0.1.4.jar",
          "size": 10818,
          "sha1": "953b0f4aa4800e1bdca0e09861c77801a8172ebc",
          "md5": "687f04ec03ecfb9832057ac5fccd94c9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "squash-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-graph",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-jdbc",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.197"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "squash-h2-jvm-0.1.4.jar",
          "url": "squash-h2-jvm-0.1.4.jar",
          "size": 10818,
          "sha1": "953b0f4aa4800e1bdca0e09861c77801a8172ebc",
          "md5": "687f04ec03ecfb9832057ac5fccd94c9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../squash-h2-metadata/0.1.4/squash-h2-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "squash-h2-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
