{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-api-rpc/0.1.4/kuick-api-rpc-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-api-rpc",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-api",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-rpc-jvm-0.1.4.jar",
          "url": "kuick-api-rpc-jvm-0.1.4.jar",
          "size": 11700,
          "sha1": "61a45985b0431541d5572901d1f70ed13f000b1b",
          "md5": "fb9f26dffd969b3062c6be161800ccfd"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-api",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-rpc-jvm-0.1.4.jar",
          "url": "kuick-api-rpc-jvm-0.1.4.jar",
          "size": 11700,
          "sha1": "61a45985b0431541d5572901d1f70ed13f000b1b",
          "md5": "fb9f26dffd969b3062c6be161800ccfd"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-api-rpc-metadata/0.1.4/kuick-api-rpc-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-api-rpc-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
