{
  "formatVersion": "1.0",
  "component": {
    "url": "../../vendor/0.1.4/vendor-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "vendor",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendor-jvm-0.1.4.jar",
          "url": "vendor-jvm-0.1.4.jar",
          "size": 261,
          "sha1": "7b3d3274f8bee9b2e8237d1562cf2d82c207db90",
          "md5": "a43e3bd794db1fa327769af2c8b114f"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "vendor-jvm-0.1.4.jar",
          "url": "vendor-jvm-0.1.4.jar",
          "size": 261,
          "sha1": "7b3d3274f8bee9b2e8237d1562cf2d82c207db90",
          "md5": "a43e3bd794db1fa327769af2c8b114f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../vendor-metadata/0.1.4/vendor-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "vendor-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
