{
  "formatVersion": "1.0",
  "component": {
    "url": "../../todo-app/0.1.4/todo-app-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "todo-app",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-http-ktor",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-db",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.soywiz",
          "module": "korte-ktor-jvm",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.soywiz",
          "module": "korte-korio-jvm",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "todo-app-jvm-0.1.4.jar",
          "url": "todo-app-jvm-0.1.4.jar",
          "size": 27312,
          "sha1": "dd4cfc9632f33b8b22c880a1214528a45e0ce573",
          "md5": "3400a1f565afa05ed4ee967fc0f9dc13"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-http-ktor",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-db",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.soywiz",
          "module": "korte-ktor-jvm",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.soywiz",
          "module": "korte-korio-jvm",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "todo-app-jvm-0.1.4.jar",
          "url": "todo-app-jvm-0.1.4.jar",
          "size": 27312,
          "sha1": "dd4cfc9632f33b8b22c880a1214528a45e0ce573",
          "md5": "3400a1f565afa05ed4ee967fc0f9dc13"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../todo-app-metadata/0.1.4/todo-app-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "todo-app-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
