{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-http/0.1.4/kuick-http-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-http",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-http-jvm-0.1.4.jar",
          "url": "kuick-http-jvm-0.1.4.jar",
          "size": 415,
          "sha1": "3272d6affc58e49ae651f851bc19e570bf7088f0",
          "md5": "3502614e99bb866d3c7f2a43231ea561"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-http-jvm-0.1.4.jar",
          "url": "kuick-http-jvm-0.1.4.jar",
          "size": 415,
          "sha1": "3272d6affc58e49ae651f851bc19e570bf7088f0",
          "md5": "3502614e99bb866d3c7f2a43231ea561"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-http-metadata/0.1.4/kuick-http-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-http-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
