{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-db/0.1.4/kuick-db-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-db",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin-coroutines",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.reactiverse",
          "module": "reactive-pg-client",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.197"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-db-jvm-0.1.4.jar",
          "url": "kuick-db-jvm-0.1.4.jar",
          "size": 176204,
          "sha1": "f0002e7ca57d43ecaa0feb01a2c5b7905a3125b4",
          "md5": "35269f212adb1ef8ae6c84fe7b2ee4f6"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin-coroutines",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.reactiverse",
          "module": "reactive-pg-client",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.197"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-db-jvm-0.1.4.jar",
          "url": "kuick-db-jvm-0.1.4.jar",
          "size": 176204,
          "sha1": "f0002e7ca57d43ecaa0feb01a2c5b7905a3125b4",
          "md5": "35269f212adb1ef8ae6c84fe7b2ee4f6"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-db-metadata/0.1.4/kuick-db-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-db-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
