{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-repositories-elasticsearch/0.1.4/kuick-repositories-elasticsearch-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-repositories-elasticsearch",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-repositories-elasticsearch-js-0.1.4.jar",
          "url": "kuick-repositories-elasticsearch-js-0.1.4.jar",
          "size": 261,
          "sha1": "2dbf79c8faa9264aa0ce573b1a14bc267f1b178f",
          "md5": "faab3e93a33e5f4a4d0d2f6d91a84968"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-repositories-elasticsearch-js-0.1.4.jar",
          "url": "kuick-repositories-elasticsearch-js-0.1.4.jar",
          "size": 261,
          "sha1": "2dbf79c8faa9264aa0ce573b1a14bc267f1b178f",
          "md5": "faab3e93a33e5f4a4d0d2f6d91a84968"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-repositories-elasticsearch-metadata/0.1.4/kuick-repositories-elasticsearch-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-repositories-elasticsearch-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
