{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-cache-redis/0.1.4/kuick-cache-redis-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-cache-redis",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-redis",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-cache-redis-js-0.1.4.jar",
          "url": "kuick-cache-redis-js-0.1.4.jar",
          "size": 261,
          "sha1": "527cdd63278e79060ff0dd433ec78650f124d12d",
          "md5": "b2570c1d6938816e31664b72acdda059"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-redis",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-cache-redis-js-0.1.4.jar",
          "url": "kuick-cache-redis-js-0.1.4.jar",
          "size": 261,
          "sha1": "527cdd63278e79060ff0dd433ec78650f124d12d",
          "md5": "b2570c1d6938816e31664b72acdda059"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-cache-redis-metadata/0.1.4/kuick-cache-redis-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-cache-redis-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
