{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-api/0.1.4/kuick-api-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-api",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-http-ktor",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-jvm-0.1.4.jar",
          "url": "kuick-api-jvm-0.1.4.jar",
          "size": 5460,
          "sha1": "3a67da7664a49de5148c799c1a55552670875aff",
          "md5": "d3e6be7f17928cd1fcc9528e3891ec2a"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-http",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-http-ktor",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-jvm-0.1.4.jar",
          "url": "kuick-api-jvm-0.1.4.jar",
          "size": 5460,
          "sha1": "3a67da7664a49de5148c799c1a55552670875aff",
          "md5": "d3e6be7f17928cd1fcc9528e3891ec2a"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-api-metadata/0.1.4/kuick-api-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-api-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
