{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-api-rest/0.1.4/kuick-api-rest-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-api-rest",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kuick-api-rest-js-0.1.4.jar",
          "url": "kuick-api-rest-js-0.1.4.jar",
          "size": 261,
          "sha1": "9c42792d9a82eb3e350ae9d59f934c69b2b3c1a8",
          "md5": "f754af5c5cef41a9747c829d56a97750"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-api-rest-js-0.1.4.jar",
          "url": "kuick-api-rest-js-0.1.4.jar",
          "size": 261,
          "sha1": "9c42792d9a82eb3e350ae9d59f934c69b2b3c1a8",
          "md5": "f754af5c5cef41a9747c829d56a97750"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-api-rest-metadata/0.1.4/kuick-api-rest-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-api-rest-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
