{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-repositories-squash/0.1.4/kuick-repositories-squash-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-repositories-squash",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.5-jre"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-h2",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-postgres",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-repositories-squash-jvm-0.1.4.jar",
          "url": "kuick-repositories-squash-jvm-0.1.4.jar",
          "size": 217325,
          "sha1": "add9db4ff3ef5242cacf206685837633e5300fc5",
          "md5": "a4b58d7d5e3e929f207fc14d310bd1c3"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.5-jre"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-h2",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "squash-postgres",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-repositories-squash-jvm-0.1.4.jar",
          "url": "kuick-repositories-squash-jvm-0.1.4.jar",
          "size": 217325,
          "sha1": "add9db4ff3ef5242cacf206685837633e5300fc5",
          "md5": "a4b58d7d5e3e929f207fc14d310bd1c3"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-repositories-squash-metadata/0.1.4/kuick-repositories-squash-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-repositories-squash-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
