{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-redis/0.1.4/kuick-redis-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-redis",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "5.1.6.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-redis-jvm-0.1.4.jar",
          "url": "kuick-redis-jvm-0.1.4.jar",
          "size": 35503,
          "sha1": "b324e59b99a748fe90f518d6997d0f13d880c18c",
          "md5": "e44c5c9b5eac82071c9c621e15acb9d3"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "5.1.6.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-redis-jvm-0.1.4.jar",
          "url": "kuick-redis-jvm-0.1.4.jar",
          "size": 35503,
          "sha1": "b324e59b99a748fe90f518d6997d0f13d880c18c",
          "md5": "e44c5c9b5eac82071c9c621e15acb9d3"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-redis-metadata/0.1.4/kuick-redis-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-redis-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
