{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-logging/0.1.4/kuick-logging-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-logging",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kuick-logging-metadata-0.1.4.jar",
          "url": "kuick-logging-metadata-0.1.4.jar",
          "size": 2656,
          "sha1": "74e70355035692504d54d84d462c8af92005b5b1",
          "md5": "73e7b6fa0a85c555e86284521eed958a"
        }
      ]
    }
  ]
}
