{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-api-rest/0.1.4/kuick-api-rest-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-api-rest",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kuick-api-rest-metadata-0.1.4.jar",
          "url": "kuick-api-rest-metadata-0.1.4.jar",
          "size": 261,
          "sha1": "ef9f743e13e790810f4ffbeb5d05ef1ecd1dc206",
          "md5": "9de0f476d89dd415862fb60ccc7acadc"
        }
      ]
    }
  ]
}
