{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-http/0.1.4/kuick-http-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-http",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kuick-http-js-0.1.4.jar",
          "url": "kuick-http-js-0.1.4.jar",
          "size": 261,
          "sha1": "8e415cc244727c457d5b86a7c485d19908272f2c",
          "md5": "fa66a90fdaf9b70f7a9877c1e96374c3"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-http-js-0.1.4.jar",
          "url": "kuick-http-js-0.1.4.jar",
          "size": 261,
          "sha1": "8e415cc244727c457d5b86a7c485d19908272f2c",
          "md5": "fa66a90fdaf9b70f7a9877c1e96374c3"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-http-metadata/0.1.4/kuick-http-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-http-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
