{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-logging/0.1.4/kuick-logging-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-logging",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kuick-logging-jvm-0.1.4.jar",
          "url": "kuick-logging-jvm-0.1.4.jar",
          "size": 16718,
          "sha1": "d6ff28ad97da711238bc7888c404c733e3973131",
          "md5": "ed28c93c6c6aba8f6f3814f1f8b07bac"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-logging-jvm-0.1.4.jar",
          "url": "kuick-logging-jvm-0.1.4.jar",
          "size": 16718,
          "sha1": "d6ff28ad97da711238bc7888c404c733e3973131",
          "md5": "ed28c93c6c6aba8f6f3814f1f8b07bac"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-logging-metadata/0.1.4/kuick-logging-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-logging-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
