{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-cache-redis/0.1.4/kuick-cache-redis-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-cache-redis",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-redis",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-cache-redis-jvm-0.1.4.jar",
          "url": "kuick-cache-redis-jvm-0.1.4.jar",
          "size": 29243,
          "sha1": "30ec9d82059c92f0b46368840530789f4dcedb3a",
          "md5": "aad616f4a2055f4a0099d2cc07d9f9ab"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nospoonlab",
          "module": "kuick-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.nospoonlab",
          "module": "kuick-redis",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-cache-redis-jvm-0.1.4.jar",
          "url": "kuick-cache-redis-jvm-0.1.4.jar",
          "size": 29243,
          "sha1": "30ec9d82059c92f0b46368840530789f4dcedb3a",
          "md5": "aad616f4a2055f4a0099d2cc07d9f9ab"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-cache-redis-metadata/0.1.4/kuick-cache-redis-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-cache-redis-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
