{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-db/0.1.4/kuick-db-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-db",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kuick-db-metadata-0.1.4.jar",
          "url": "kuick-db-metadata-0.1.4.jar",
          "size": 261,
          "sha1": "2aa1dedfa6f4ce34d93f74ee78851c58b48f9d4e",
          "md5": "d35c590c5279e09607698edc1523877d"
        }
      ]
    }
  ]
}
