{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kuick-logging/1.5-cherry/kuick-logging-1.5-cherry.module",
    "group": "com.nospoonlab",
    "module": "kuick-logging",
    "version": "1.5-cherry",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7d5yqdf2p5ccrnoaxcra5nglum"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kuick-logging-jvm-1.5-cherry.jar",
          "url": "kuick-logging-jvm-1.5-cherry.jar",
          "size": 16727,
          "sha512": "3edaebe9b4f59cb0ce99d123d7a0f0535447a284d441a470f1950f20be382a2a83b571fd686a70ebe377a95f516d9b1afed5121b649a6f957014bac21b3a1580",
          "sha256": "32396c0067fb8cfe07f42ab1c971a52f6d9ac211840f3b0cdfcc21ce9eac3098",
          "sha1": "8d3884ce433045988b7cb490e8a83891138769e4",
          "md5": "0d2aa8de8a904d3e4b05bf2e55161e79"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-logging-jvm-1.5-cherry.jar",
          "url": "kuick-logging-jvm-1.5-cherry.jar",
          "size": 16727,
          "sha512": "3edaebe9b4f59cb0ce99d123d7a0f0535447a284d441a470f1950f20be382a2a83b571fd686a70ebe377a95f516d9b1afed5121b649a6f957014bac21b3a1580",
          "sha256": "32396c0067fb8cfe07f42ab1c971a52f6d9ac211840f3b0cdfcc21ce9eac3098",
          "sha1": "8d3884ce433045988b7cb490e8a83891138769e4",
          "md5": "0d2aa8de8a904d3e4b05bf2e55161e79"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-logging-metadata/1.5-cherry/kuick-logging-metadata-1.5-cherry.module",
        "group": "com.nospoonlab",
        "module": "kuick-logging-metadata",
        "version": "1.5-cherry"
      }
    }
  ]
}
