{
  "formatVersion": "1.0",
  "component": {
    "url": "../../samples/0.1.4/samples-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "samples",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "samples-jvm-0.1.4.jar",
          "url": "samples-jvm-0.1.4.jar",
          "size": 261,
          "sha1": "decdf5bfe704aaa19a91cee5b0046f4299bff54",
          "md5": "475dae737c5a11068b5c69002243c39e"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "samples-jvm-0.1.4.jar",
          "url": "samples-jvm-0.1.4.jar",
          "size": 261,
          "sha1": "decdf5bfe704aaa19a91cee5b0046f4299bff54",
          "md5": "475dae737c5a11068b5c69002243c39e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../samples-metadata/0.1.4/samples-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "samples-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
