{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kuick-logging/0.1.4/kuick-logging-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "kuick-logging",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kuick-logging-js-0.1.4.jar",
          "url": "kuick-logging-js-0.1.4.jar",
          "size": 39754,
          "sha1": "e11373a06fb5936c4c6c7221893f33970624259e",
          "md5": "a2caed7041e95d6925384f981742132d"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "kuick-logging-js-0.1.4.jar",
          "url": "kuick-logging-js-0.1.4.jar",
          "size": 39754,
          "sha1": "e11373a06fb5936c4c6c7221893f33970624259e",
          "md5": "a2caed7041e95d6925384f981742132d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kuick-logging-metadata/0.1.4/kuick-logging-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "kuick-logging-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
