{
  "formatVersion": "1.0",
  "component": {
    "url": "../../squash-core/0.1.4/squash-core-0.1.4.module",
    "group": "com.nospoonlab",
    "module": "squash-core",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "l6qbeazn4jftde4cgeinfmqdae"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "squash-core-jvm-0.1.4.jar",
          "url": "squash-core-jvm-0.1.4.jar",
          "size": 175549,
          "sha1": "2b29fa02676f65800e75d635df8939f604e5d1f5",
          "md5": "1de296d4047f1592f37116cc3e2ed746"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        }
      ],
      "files": [
        {
          "name": "squash-core-jvm-0.1.4.jar",
          "url": "squash-core-jvm-0.1.4.jar",
          "size": 175549,
          "sha1": "2b29fa02676f65800e75d635df8939f604e5d1f5",
          "md5": "1de296d4047f1592f37116cc3e2ed746"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../squash-core-metadata/0.1.4/squash-core-metadata-0.1.4.module",
        "group": "com.nospoonlab",
        "module": "squash-core-metadata",
        "version": "0.1.4"
      }
    }
  ]
}
